

-- Table: Users
CREATE TABLE Client (
    Client_id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Artist(
    Artist_id SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Table: Artists
CREATE TABLE Artistdashboard (
    service_id INT AUTO_INCREMENT PRIMARY KEY,
    Artist_id INT NOT NULL REFERENCES Artist(Artist_id) ON DELETE CASCADE,
    BrandName VARCHAR(200) NOT NULL,
    Address VARCHAR(200) NOT NULL,
    Location VARCHAR(200) NOT NULL,
    Fileurl VARCHAR(2000) NOT NULL,
    ContactNumber VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: Services
CREATE TABLE Services (
    Service_id SERIAL PRIMARY KEY,
    Artist_id INT NOT NULL REFERENCES Artist(Artist_id) ON DELETE CASCADE,
    Service_name VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Duration INT NOT NULL, -- in minutes
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: Appointments
CREATE TABLE Booking (
    Booking_id SERIAL PRIMARY KEY,
    Artist_id INT NOT NULL REFERENCES Artist(Artist_id) ON DELETE CASCADE,
    Client_id INT NOT NULL REFERENCES Client(Client_id) ON DELETE CASCADE,
    Service_id INT NOT NULL REFERENCES Service(Service_id) ON DELETE CASCADE,
    Booking_date DATETIME NOT NULL,
    Comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: Reviews
CREATE TABLE Reviews (
    Review_id SERIAL PRIMARY KEY,
    Artist_id INT NOT NULL REFERENCES Artist(Artist_id) ON DELETE CASCADE,
    Client_id INT NOT NULL REFERENCES Client(Client_id) ON DELETE CASCADE,
    Rating INT CHECK (rating BETWEEN 1 AND 5),
    Comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

